repos:
    -   repo: https://github.com/pre-commit/pre-commit-hooks
        rev: v2.3.0
        hooks:
            -   id: check-yaml
            -   id: end-of-file-fixer
            -   id: trailing-whitespace
    -   repo: git://github.com/dnephin/pre-commit-golang
        rev: master
        hooks:
            -   id: golangci-lint
#            -   id: go-fmt
#            -   id: go-vet
#            -   id: go-lint
#            -   id: go-imports
#            -   id: go-cyclo
#                args: [-over=15]
#            -   id: validate-toml
#            -   id: no-go-testing
#            -   id: gometalinter
#            -   id: go-critic
#            -   id: go-unit-tests
#            -   id: go-build
#            -   id: go-mod-tidy
